description: Travel APIs for Flights, Hotels, Car rental by Allmyles. The only Global Travel booking API provides access to bookable travel content to build innovative web or native apps.
url: "https://allmyles.com"
permalink: pretty


exclude:
  - vendor
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
